name: Test react app
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repos
        uses: actions/checkout@v6
      - name: Install depend
        run: npm Install
      - name: Test app
        run: npm run test